### ISSUE TITLE
Document the anarchy.conf variables

### ISSUE THREAD

**Issue by magnunleno** [magnunleno/Anarchy#4]
Document all anarchy.conf variables in a wiki page.

**Comment by hmleal** [comment]
A Little Less Conversation =)

Added Link to this page in home of wiki
https://github.com/magnunleno/Anarchy/wiki/Anarchy.conf

**Comment by hmleal** [comment]
Next
Improve description of variables

**Comment by magnunleno** [comment]
Closed by now. Will improve in the next version.
